{
  imports = [
    ./stylix.nix
    ./editing.nix
    ./greetd.nix
    ./plymouth.nix
    ./browser.nix
    ./printing.nix
    ./networking.nix
    ./misc.nix
    ./gaming.nix
    ./factorio.nix
    ./zfs.nix
    ./boot.nix
    ./niri.nix
    ./sound.nix
    ./users.nix
    ./terminal.nix
    ./socialize.nix
    ./no-shutdown.nix
    ./localization.nix
    ./nixvim/nixvim.nix
    #./treefmt.nix
  ];
}
